version: '3'

services:
  web:
    build: ./web
    ports:
      - "5000:80"
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - "9200:9200"
      - "9300:9300"