elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
# web:
#   build: ./web
#   ports:
#     - "5000:80"
#   links:
#     - api
api:
  build: ./api
  ports:
    - "3000:3000"
  links:
    - elasticsearch