elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
rabbitmq:
  image: rabbitmq:3.7.2
  ports:
    - "5672:5672"
api:
  build: ./api
  ports:
    - "3000:3000"
  links:
    - elasticsearch
    - rabbitmq
web:
  build: ./web
  ports:
    - "5000:80"
  links:
    - api